### ISSUE TITLE
version 0.67 fails to install with composer

### ISSUE THREAD

**Issue by robtesch** [google/google-api-php-client-services#130]
The process "unzip -qq ...." exceeded the timeout of 300 seconds.
    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class.

After waiting for a long time it eventually just fails. Forcing v0.66 seems to fix the issue for now.

**Comment by squierll** [comment]
Also if i try install v.066, i get an error:

```
 Installing google/apiclient-services (v0.66): Loading from cache

    The process "unzip -qq  '/home/vagrant/code/myapp/vendor/google/apiclient-services/ccade3f9b0b93619d73653e0387dd1b0' -d '/home/vagrant/code/myapp/vendor/composer/dccb3b56'" exceeded the timeout of 300 seconds.
    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class

```

**Comment by robtesch** [comment]
@squierll you're right. I spoke too soon, that's not working either.

**Comment by robtesch** [comment]
OK, i honestly don't know what happened, but I just tried to do another composer update (with v0.67) and this time it randomly worked.

**Comment by marcpre** [comment]
When I use the cmd on windows I get the error. When I use the git-bash, everything seems to work fine.

**Comment by mattwhisenhunt** [comment]
@robtesch , @squierll can you both confirm you are seeing this issue on Windows?

**Comment by squierll** [comment]
@mattwhisenhunt : Yes.

**Comment by robtesch** [comment]
@mattwhisenhunt issue was on Ubuntu 16.04 vagrant (using composer within the VM) with a Windows host. As mentioned, the issue has now magically resolved itself, so might have been a more general issue with my VM which got fixed after rebooting it.

**Comment by mattwhisenhunt** [comment]
Thanks for details. I will look into this but am going to close this issue for now.

**Comment by coldshine** [comment]
I had the same issue. I'm running docker machine on a Windows Home host. Deleting `vendor/google/apiclient-services` did not help.
When I tried to run unzip command without -qq flag directly to the file in `vendor/google/apiclient-services`, it seems like the unzipping was successful. The problem was in the speed of extraction. In this archive there are about 10k files, so it takes pretty much time to unzip on my VM. The error tells us that uznip exceeded the timeout of 300 seconds, but real unzipping took quite longer time. This timeout is set by composer, so increasing it to 600 seconds `export COMPOSER_PROCESS_TIMEOUT=600` did help me to solve the issue.

**Comment by rei-gun** [comment]
+1
