### ISSUE TITLE
Google_Service_Translate_TranslationsListResponse->getTranslations() returns empty

### ISSUE THREAD

**Issue by stevevg** [google/google-api-php-client-services#38]
```
$client = new \Google_Client();
$client->setApplicationName(APP_NAME);
$client->setDeveloperKey(API_KEY);

$service = new \Google_Service_Translate($client);
$translations = $service->translations->listTranslations("hello", "it", ["source" => "en", "format" => "html"])->getTranslations();
var_dump($translations);
```

This code returns empty, instead of the translations.
I edited my own code (see #37) and it works correctly. If this is not a bug but a desired behaviour, I may suggest considering a better way to document this API.

**Comment by mattwhisenhunt** [comment]
Thank you for your bug report. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to fix this bug since there is an acceptable work-around. If you disagree, please feel free to re-open this issue and explain why you believe fixing it is essential for users of this client library.

**Comment by stevevg** [comment]
Hi,
I'd like to keep this open, since the translation service has a bug which makes it impossible to get the translations.
The PR #37 that I proposed solves this issue. This is no workaround, it is the only way I found to get the translations out of the Google Translate Service using this library, but I needed to fork the project.

If there is a workaround using your codebase, I'd like to know what it is, so I can switch my projects towards your releases, instead of using mine.
