### ISSUE TITLE
Google My Business API Support

### ISSUE THREAD

**Issue by jsiebach** [google/google-api-php-client-services#60]
The API library is here: https://developers.google.com/my-business/samples/

I am still having to autoload this separately from the rest of the API services, is this a planned integration?

Thanks

**Comment by AlexECP** [comment]
@jsiebach im also having this trouble, but I have not been able to autoload it properly, can you tell me how you did it?

**Comment by jsiebach** [comment]
I am using a Laravel app and created a subfolder outside of my autoload directory which I added to my `composer.json`:

```
"autoload": {
        "classmap": [
            "database",
            "resources/unnamespaced/MyBusiness.php"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
```

**Comment by AlexECP** [comment]
@jsiebach thanks, that worked

**Comment by mattwhisenhunt** [comment]
To answer your original question, that plan is up to the [My Business API team](https://developers.google.com/my-business/content/support). As soon they publish to the root discovery document that library will be automatically available here.

**Comment by mfn** [comment]
I don't want to create noise with a new issue as I'm currently not _yet affected, but currently that library is defined as
```php
class Google_Service_MyBusiness extends Google_Service
```
In 2.*, `Google_Service` was replaced with an alias to `Google\Service` which will be removed eventually.

Since it seems they're still not yet added to the root discovery, I hope someone has it on their agenda to provide compatibility here? 🤔
