### ISSUE TITLE
Mistakes in autogenerated phpdoc

### ISSUE THREAD

**Issue by vdechenaux** [google/google-api-php-client-services#88]
Hi,

There is a mistake on getters/setters which returns/takes an array of object.
For example: https://github.com/google/google-api-php-client-services/blob/0805897f3435f9eea73ce21da9d55f51c69c1171/src/Google/Service/YouTube/CommentThreadListResponse.php#L56-L59
It should be `@return Google_Service_YouTube_CommentThread[]`

I didn't opened a PR because it seems to be autogenerated.

Thanks!

**Comment by mattwhisenhunt** [comment]
Thank you for your bug report. Even the python project that generates this library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs. After careful consideration, we have decided not to fix this bug since there is an acceptable work-around. If you disagree, please feel free to re-open this issue and explain why you believe fixing it is essential for users of this client library.
